### ISSUE TITLE
Disable Safe-Mode with userChrome.css

### ISSUE THREAD

**Issue by Metaception** [proginosko/LeechBlockNG#12]
Since webextensions can't modify the browser UI, you need to use the userChrome.css file. May I suggest the following CSS to hide the **Restart with Add-ons Disabled…** option:

`
toolbarbutton[label='Restart with Add-ons Disabled…'] {
visibility: collapse !important;
}
`

You can put it in the addon description or the FAQ if anyone needs it.
I am not the best at CSS so it could be refined a bit.

You can also [disable the Safe-Mode key trigger](https://bugzilla.mozilla.org/show_bug.cgi?id=1140183) with an environment variable, but I am not sure if you would want users to mess with the environment variables.

**P.S.** Do you still need the option to block about:config? I can understand about:support, but LeechBlockNG doesn't store it's settings in about:config anymore so it is a bit moot.

**Comment by proginosko** [comment]
Good point re about:config. I should take that out.

**Comment by proginosko** [comment]
I just tested your userChrome.css solution. (Sorry it took so long to get around to it!)

Works a treat. One minor tweak to make it locale-independent:

`#helpSafeMode { visibility: collapse !important; }`

I will put this in the FAQ and give you credit.

**Comment by Metaception** [comment]
I can't get the new code to work. I am on Win 10.

I have found references to the new code, but they suggest `display: none` instead of `visibility: collapse`. I can't get that to work either though.

**Comment by proginosko** [comment]
What do you mean by "the new code"?

**Comment by Metaception** [comment]
The new CSS selector `#helpSafeMode`

**Comment by proginosko** [comment]
Does your original version (with `toolbarbutton` selector) still work on your system?

**Comment by Metaception** [comment]
Yes, it works on both Win 10 and Ubuntu 16.

Which systems did you test on?

**Comment by proginosko** [comment]
Win 10.

So if you just change the selector in userChrome.css to `#helpSafeMode` it stops working for you?

**Comment by Metaception** [comment]
Yeah, the entry is still there in the help menu

**Comment by proginosko** [comment]
Would you mind emailing me (leechblockng@proginosko.com) your userChrome.css file (the latest one, which doesn't work)?

**Comment by Metaception** [comment]
'
@namespace url('http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul');

#helpSafeMode {
    visibility: collapse !important;
}
'

**Comment by proginosko** [comment]
It's just occurred to me that we may be looking at different menus! I realize now that my version only hides the item in the Help menu in the Menu Bar. It doesn't hide the item in the pop-out side menu (where the Help menu has a question mark icon next to it). Does that explain your report here?

**Comment by Metaception** [comment]
Ohhhh, yeah that would explain it.

Yeah, my code is for the hamburger menu.

I can confirm that the menu bar version is hidden by your code.

**Comment by Metaception** [comment]
I tested and fine tuned the code a bit more:
```
@namespace url('http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul');

/* Disable safe mode buttons in menu bar and hamburger menu */
#helpSafeMode,
toolbarbutton.subviewbutton[label='Restart with Add-ons Disabled…'] {
    visibility: collapse !important;
}
```
Both buttons are blocked now!

**Comment by proginosko** [comment]
Thanks. I was hoping to find a locale-independent solution, hence the use of the # id selector. But it looks like Firefox generates the hamburger Help menu from the main Help menu, and it either assigns the same id to the menu item (bad form!) or doesn't assign one at all.

So I think this is the simplest solution for now:

`[label^='Restart with Add-ons Disabled'] { display: none !important; }`

This hides the item in both menus. It also avoids the user having to enter the ellipsis character (which can easily be confused with three periods).

**Comment by Metaception** [comment]
Great, should we close this issue again then?

**Comment by rm-rf0** [comment]
Sorry to reopen this issue.

Following the step above, I am able to hide the **Restart with Add-ons Disabled…** option in the pop-out side menu, but it still exists in Help menu (in the Menu Bar).

I am using MacOS Mojave, and my `userChrome.css` looks like this:

```css
[label^='Restart with Add-ons Disabled'] { display: none !important; }
```

Also, I have tried

```css
@namespace url('http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul');

/* Disable safe mode buttons in menu bar and hamburger menu */
#helpSafeMode,
toolbarbutton.subviewbutton[label='Restart with Add-ons Disabled…'] {
    visibility: collapse !important;
}
```

and 

```css
@namespace url('http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul');

/* Disable safe mode buttons in menu bar and hamburger menu */
#helpSafeMode,
toolbarbutton.subviewbutton[label='Restart with Add-ons Disabled…'] {
    display:none !important;
}
```

None of them works for me.
